version: '3.8'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/pg:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5656:5432